// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectoVia.Models.KompaniaTaksive;

#nullable disable

namespace vectovia.Migrations
{
    [DbContext(typeof(KompaniaTaxiDbContext))]
    [Migration("20240522152020_migrimiA")]
    partial class migrimiA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.KompaniaQyteti", b =>
                {
                    b.Property<int>("KompaniaTaxiId")
                        .HasColumnType("int");

                    b.Property<int>("QytetiId")
                        .HasColumnType("int");

                    b.HasKey("KompaniaTaxiId", "QytetiId");

                    b.HasIndex("QytetiId");

                    b.ToTable("KompaniaTaxiQytetis");
                });

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.KompaniaTaxi", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kompania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qyteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigurimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.ToTable("KompaniaTaxis");
                });

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.Qyteti", b =>
                {
                    b.Property<int>("QytetiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QytetiId"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QytetiId");

                    b.ToTable("Qytetis");
                });

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.KompaniaQyteti", b =>
                {
                    b.HasOne("vectovia.Models.KompaniaTaksive.Model.KompaniaTaxi", "KompaniaTaxii")
                        .WithMany("KompaniaTaxiQytetis")
                        .HasForeignKey("KompaniaTaxiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vectovia.Models.KompaniaTaksive.Model.Qyteti", "Qyteti")
                        .WithMany("KompaniaTaxiQytetis")
                        .HasForeignKey("QytetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KompaniaTaxii");

                    b.Navigation("Qyteti");
                });

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.KompaniaTaxi", b =>
                {
                    b.Navigation("KompaniaTaxiQytetis");
                });

            modelBuilder.Entity("vectovia.Models.KompaniaTaksive.Model.Qyteti", b =>
                {
                    b.Navigation("KompaniaTaxiQytetis");
                });
#pragma warning restore 612, 618
        }
    }
}
