// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectoVia.Models.TaxiCars;

#nullable disable

namespace VectoVia.Migrations
{
    [DbContext(typeof(TaxiCarsDbContext))]
    partial class TaxiCarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VectoVia.Models.TaxiCars.Model.TaxiCar", b =>
                {
                    b.Property<string>("Targat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TaxiID")
                        .HasColumnType("int");

                    b.Property<int>("hapesiraNeBagazh")
                        .HasColumnType("int");

                    b.Property<bool>("iDisponueshem")
                        .HasColumnType("bit");

                    b.Property<string>("llojiKarburantit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("llojiVetures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nrPassenger")
                        .HasColumnType("int");

                    b.HasKey("Targat");

                    b.ToTable("TaxiCars");
                });
#pragma warning restore 612, 618
        }
    }
}
